/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author The Programmer
 */
public class admin extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public admin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        add_user = new javax.swing.JButton();
        delete_user = new javax.swing.JButton();
        edit_user = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Homepage");
        setLocation(new java.awt.Point(230, 100));
        setMaximumSize(new java.awt.Dimension(662, 439));
        setMinimumSize(new java.awt.Dimension(662, 439));
        setPreferredSize(new java.awt.Dimension(662, 439));
        setResizable(false);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(36, 46, 68));

        add_user.setBackground(new java.awt.Color(204, 204, 204));
        add_user.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        add_user.setForeground(new java.awt.Color(255, 255, 255));
        add_user.setText("Add User");
        add_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 246, 243), 2, true));
        add_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_user.setOpaque(false);
        add_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                add_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                add_userMouseExited(evt);
            }
        });
        add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_userActionPerformed(evt);
            }
        });

        delete_user.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        delete_user.setForeground(new java.awt.Color(255, 255, 255));
        delete_user.setText("Delete User");
        delete_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 246, 243), 2, true));
        delete_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                delete_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                delete_userMouseExited(evt);
            }
        });
        delete_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_userActionPerformed(evt);
            }
        });

        edit_user.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        edit_user.setForeground(new java.awt.Color(255, 255, 255));
        edit_user.setText("Edit User");
        edit_user.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(154, 246, 243), 2, true));
        edit_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        edit_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edit_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edit_userMouseExited(evt);
            }
        });
        edit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_userActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(210, 210, 210)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(delete_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(add_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(edit_user, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap(205, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(add_user, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addComponent(edit_user, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(delete_user, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67))
        );

        add_user.setContentAreaFilled(false);
        delete_user.setContentAreaFilled(false);
        edit_user.setContentAreaFilled(false);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 660, 420);

        jMenu1.setText("File");

        exit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.ALT_MASK));
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu1.add(exit);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void delete_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_userActionPerformed
    Delete_user dialog = null;
                try {
                    dialog = new Delete_user(new javax.swing.JFrame(), true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Delete_user.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Delete_user.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);       
    }//GEN-LAST:event_delete_userActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
       System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_userActionPerformed
          Add_user dialog = null;
                try {

                    dialog = new Add_user(new javax.swing.JFrame(), true);
                } catch (SQLException ex) {
                    Logger.getLogger(Add_user.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Add_user.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
    }//GEN-LAST:event_add_userActionPerformed

    private void add_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userMouseEntered
       add_user.setOpaque(true);
       add_user.setContentAreaFilled(true);
       //hod.setForeground(new Color(0,0,51));

        add_user.setBackground(new Color(14,42,160));
    }//GEN-LAST:event_add_userMouseEntered

    private void add_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_userMouseExited
        add_user.setOpaque(false);
       add_user.setContentAreaFilled(false);
 //      hod.setForeground(Color.white);
    }//GEN-LAST:event_add_userMouseExited

    private void delete_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_userMouseEntered
        delete_user.setOpaque(true);
       delete_user.setContentAreaFilled(true);
       //hod.setForeground(new Color(0,0,51));

        delete_user.setBackground(new Color(14,42,160));
    }//GEN-LAST:event_delete_userMouseEntered

    private void delete_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_delete_userMouseExited
  delete_user.setOpaque(false);
       delete_user.setContentAreaFilled(false);    }//GEN-LAST:event_delete_userMouseExited

    private void edit_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_userMouseEntered
                    edit_user.setOpaque(true);
       edit_user.setContentAreaFilled(true);
       //hod.setForeground(new Color(0,0,51));

        edit_user.setBackground(new Color(14,42,160));
    }//GEN-LAST:event_edit_userMouseEntered

    private void edit_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edit_userMouseExited
       edit_user.setOpaque(false);
       edit_user.setContentAreaFilled(false);
      
    }//GEN-LAST:event_edit_userMouseExited

    private void edit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_userActionPerformed
         Edit_user dialog = null;
                try {
                    dialog = new Edit_user(new javax.swing.JFrame(), true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Edit_user.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(Edit_user.class.getName()).log(Level.SEVERE, null, ex);
                }
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
    }//GEN-LAST:event_edit_userActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_user;
    private javax.swing.JButton delete_user;
    private javax.swing.JButton edit_user;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
